// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhVjN6gv4QdpuN082DgANvxnUcfUo848',
    appId: '1:714178415618:web:9f057e1094b12206e92b1b',
    messagingSenderId: '714178415618',
    projectId: 'todoapp-6324e',
    authDomain: 'todoapp-6324e.firebaseapp.com',
    storageBucket: 'todoapp-6324e.appspot.com',
    measurementId: 'G-B1CT57MRTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQwJbqQWLtrTMNKnTW17GtXUIw3KMefb0',
    appId: '1:714178415618:android:b28c62f10251cfcfe92b1b',
    messagingSenderId: '714178415618',
    projectId: 'todoapp-6324e',
    storageBucket: 'todoapp-6324e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0eCK6WfASjqiVhHR5YYmm4GqVndBPUs',
    appId: '1:714178415618:ios:195c66c7fde85ff8e92b1b',
    messagingSenderId: '714178415618',
    projectId: 'todoapp-6324e',
    storageBucket: 'todoapp-6324e.appspot.com',
    iosClientId: '714178415618-51od2e2rkhms8cr7040m4ehr049b24rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ0eCK6WfASjqiVhHR5YYmm4GqVndBPUs',
    appId: '1:714178415618:ios:195c66c7fde85ff8e92b1b',
    messagingSenderId: '714178415618',
    projectId: 'todoapp-6324e',
    storageBucket: 'todoapp-6324e.appspot.com',
    iosClientId: '714178415618-51od2e2rkhms8cr7040m4ehr049b24rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
